### ISSUE TITLE
Search is not working in common autocomplete for ""thematicAutoComplete" 

### ISSUE THREAD

**Issue by inspiremithun** [Tenmak/material#1]
Search is not working

**Comment by Tenmak** [comment]
It is normal, this repository, as the readme states, is only a mock of an existing application in order to work on creating a custom autocomplete component. 
This one has an issue, and this repository was used as a link for a Stack Overflow question : https://stackoverflow.com/questions/48994456/angular-material-custom-autocomplete-component
